services:
  postgres:
    image: postgres:16-alpine
    container_name: kurtuba-auth-postgres
    environment:
      POSTGRES_DB: kurtuba_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - kurtuba-auth-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kurtuba_auth"]
      interval: 5s
      timeout: 5s
      retries: 20

  mailpit:
    image: axllent/mailpit:v1.26
    container_name: kurtuba-auth-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:7-alpine
    container_name: kurtuba-auth-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  kurtuba-auth-postgres-data:
