package com.kurtuba.auth.utils;

import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken;
import com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.gson.GsonFactory;
import com.kurtuba.auth.data.dto.UserRegistrationDto;
import com.kurtuba.auth.data.enums.AuthProviderType;
import com.kurtuba.auth.error.enums.ErrorEnum;
import com.kurtuba.auth.error.exception.BusinessLogicException;
import com.nimbusds.jose.shaded.gson.JsonArray;
import com.nimbusds.jose.shaded.gson.JsonObject;
import com.nimbusds.jose.shaded.gson.JsonParser;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtBuilder;
import io.jsonwebtoken.Jwts;
import jakarta.annotation.PostConstruct;
import org.jose4j.jwe.JsonWebEncryption;
import org.jose4j.jwk.PublicJsonWebKey;
import org.jose4j.keys.PbkdfKey;
import org.jose4j.lang.JoseException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;
import org.springframework.util.CollectionUtils;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;

@Component
public class TokenUtils {

    @Value("${kurtuba.rsa-jwk.secrets}")
    private String rsaJwkSecrets;
    @Value("classpath:rsa-jwk.json")
    Resource rsaJwkFile;
    @Value("${auth.server.issuer-url}")
    private String authServerIssuerUrl;

    private PublicJsonWebKey currentPublicJsonWebKey;

    private List<PublicJsonWebKey> allSigningKeys;

    @PostConstruct
    public void init() {
        allSigningKeys = decryptJwk();
        currentPublicJsonWebKey = allSigningKeys.get(0);
    }

    /**
     * Generates an access token for login via rest request
     *
     * @param userId
     * @param auds
     * @param duration
     * @return Access token
     */
    public String generateToken(String userId, Set<String> auds, Set<String> scopes, Duration duration) {
        JwtBuilder builder = Jwts.builder()
                .header()
                .keyId(currentPublicJsonWebKey.getKeyId())
                .and()
                .id(UUID.randomUUID().toString())
                .issuer(authServerIssuerUrl)
                .subject(userId)
                .audience()
                .add(auds)
                .and()
                .issuedAt(new Date())
                .notBefore(new Date())
                .expiration(Date.from(LocalDateTime.now().plus(duration).atZone(ZoneId.systemDefault()).toInstant()));

        if (!CollectionUtils.isEmpty(scopes))
            builder = builder.claim("scope", scopes.toString());


        return builder
                .signWith(currentPublicJsonWebKey.getPrivateKey())
                .compact();
    }

    public String generateRefreshToken() {
        String originalBase64String = Base64.getEncoder().encodeToString(UUID.randomUUID().toString().getBytes());
        final MessageDigest digest;
        try {
            digest = MessageDigest.getInstance("SHA3-256");
        } catch (NoSuchAlgorithmException e) {
            throw new BusinessLogicException(ErrorEnum.GENERIC_EXCEPTION.getCode()
                    , "SHA3-256 algorithm not found. Unable to create refresh token");
        }
        final byte[] hashBytes = digest.digest(
                originalBase64String.getBytes(StandardCharsets.UTF_8));
        String sha3Hex = bytesToHex(hashBytes);
        return Base64.getEncoder().encodeToString(sha3Hex.getBytes());
    }

    private static String bytesToHex(byte[] hash) {
        StringBuilder hexString = new StringBuilder(2 * hash.length);
        for (int i = 0; i < hash.length; i++) {
            String hex = Integer.toHexString(0xff & hash[i]);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }
        return hexString.toString();
    }

    /**
     * Returns claims of token generated by this auth server
     * Uses signing keys to verify during decoding
     *
     * @param token
     * @return
     */
    public Claims getVerifiedTokenClaims(String token, long clockSkew) {

        String keyId = decodeTokenHeader(token).getAsJsonObject().get("kid").getAsString();

        // find the key
        PublicJsonWebKey webKey = decryptJwk().stream().filter(key ->
                key.getKeyId().equals(keyId)).findFirst().orElse(null);

        if (webKey == null) {
            throw new BusinessLogicException(ErrorEnum.AUTH_INVALID_TOKEN);
        }

        Claims claims = (Claims) Jwts.parser()
                .clockSkewSeconds(clockSkew)
                .verifyWith(webKey.getPublicKey())
                .build()
                .parse(token).getPayload();

        return claims;
    }

    /**
     * Decrypts keys in rsa-jwk.json using secrets in properties.yaml
     * Returns the keys sorted(descending) according to "order" property in rsa-jwk.json file
     *
     * @return
     */
    public List<PublicJsonWebKey> decryptJwk() {
        try {
            String rsaJwkContents = rsaJwkFile.getContentAsString(StandardCharsets.UTF_8);
            JsonObject rsaJwkJson = JsonParser.parseString(rsaJwkContents).getAsJsonObject();
            JsonArray encryptedKeys = rsaJwkJson.get("keys").getAsJsonArray();
            JsonObject secretsJson = JsonParser.parseString(rsaJwkSecrets).getAsJsonObject();
            Map<Integer, PublicJsonWebKey> orderedKeys = new HashMap<>();
            encryptedKeys.asList().stream().forEach(encryptedKeyJson -> {
                String secret = secretsJson.get(encryptedKeyJson.getAsJsonObject().get("id").getAsString()).getAsString().toString();
                String jwkEncrypted = encryptedKeyJson.getAsJsonObject().get("encryptedKey").getAsString();
                JsonWebEncryption decryptingJwe = new JsonWebEncryption();
                try {
                    decryptingJwe.setCompactSerialization(jwkEncrypted);
                    decryptingJwe.setKey(new PbkdfKey(secret));
                    orderedKeys.put(encryptedKeyJson.getAsJsonObject().get("order").getAsInt(), PublicJsonWebKey.Factory.newPublicJwk(decryptingJwe.getPayload()));
                } catch (JoseException e) {
                    throw new RuntimeException(e);
                }
            });
            return orderedKeys.keySet().stream().sorted((id1, id2) -> Integer.compare(id2, id1)).map(order -> orderedKeys.get(order)).toList();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * Decodes and verifies google access token
     *
     * @param idTokenString token given by google
     * @param clientId      clientId used to get the token(Android clientId or iOS clientId)
     * @throws GeneralSecurityException
     * @throws IOException
     */
    public static UserRegistrationDto decodeGoogleToken(String idTokenString, String clientId) throws GeneralSecurityException, IOException {
        UserRegistrationDto newUser = new UserRegistrationDto();
        GoogleIdTokenVerifier verifier = new GoogleIdTokenVerifier.Builder(new NetHttpTransport(), new GsonFactory())
                // Specify the CLIENT_ID of the app that accesses the backend:
                .setAudience(Collections.singletonList(clientId))
                // Or, if multiple clients access the backend:
                //.setAudience(Arrays.asList(CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3))
                .build();

        // (Receive idTokenString by HTTPS POST)

        GoogleIdToken idToken = verifier.verify(idTokenString);
        if (idToken != null) {
            GoogleIdToken.Payload payload = idToken.getPayload();

            // Print user identifier
            String userId = payload.getSubject();
            System.out.println("User ID: " + userId);

            // Get profile information from payload
            String email = payload.getEmail();
            String familyName = (String) payload.get("family_name");
            String givenName = (String) payload.get("given_name");
            newUser.setEmail(email);
            newUser.setName(givenName);
            newUser.setSurname(familyName);
            newUser.setAuthProvider(AuthProviderType.GOOGLE);

        } else {
            System.out.println("Invalid ID token.");
        }

        return newUser;
    }

    /**
     * Generic token payload decoder
     *
     * @param tokenString
     * @return JsonObject
     */
    public static JsonObject decodeTokenPayload(String tokenString) {
        String[] split_string = tokenString.split("\\.");
        String base64EncodedBody = split_string[1];
        Base64.Decoder base64Url = Base64.getDecoder();
        String body = new String(base64Url.decode(base64EncodedBody));

        return JsonParser.parseString(body).getAsJsonObject();

    }

    public static JsonObject decodeTokenHeader(String tokenString) {
        String[] split_string = tokenString.split("\\.");
        String base64EncodedHeader = split_string[0];
        Base64.Decoder base64Url = Base64.getDecoder();
        String header = new String(base64Url.decode(base64EncodedHeader));

        return JsonParser.parseString(header).getAsJsonObject();

    }

    public static void main(String[] args) {
        /*
        String idToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijg1MmI0Yzc0MTM1MWVlZGM2ZWM4YWU3ODNiOThlZWFiZTIxNTdkYWEifQ.eyJpc3MiOiJodHRwczpcL1wvd3d3LmZhY2Vib29rLmNvbSIsImF1ZCI6IjE3ODg1Nzc5ODA3Njc1NiIsInN1YiI6IjEwMTU5MjAxMTgwNTI3Nzk3IiwiaWF0IjoxNjg2ODMxMTU4LCJleHAiOjE2ODY4MzQ3NTgsImp0aSI6IlJ5VWMuNGM5ZWZlY2NjYTAyOWZjNjFmZDU5ZWUwZDBlODdmM2Q4ZTA0ZTgwNDU2MjUyMjE3OTZhNDBhODBiMDJkYjhiZiIsIm5vbmNlIjoiIiwiYXRfaGFzaCI6IlV1Q3V5eXNPQmsxRE1wSTY0TWppbEEiLCJlbWFpbCI6Im11cmF0Y2FuZXJcdTAwNDB5bWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiTXVyYXQiLCJmYW1pbHlfbmFtZSI6IkNhbmVyIiwibmFtZSI6Ik11cmF0IENhbmVyIiwicGljdHVyZSI6Imh0dHBzOlwvXC9wbGF0Zm9ybS1sb29rYXNpZGUuZmJzYnguY29tXC9wbGF0Zm9ybVwvcHJvZmlsZXBpY1wvP2FzaWQ9MTAxNTkyMDExODA1Mjc3OTcmaGVpZ2h0PTEwMCZ3aWR0aD0xMDAmZXh0PTE2ODk0MjMxNTkmaGFzaD1BZVFVRk5PbC02eUo5cndKU2w0In0.tC1fqzT7E_gJlSAYq9PXJYs7bQ2R03RbB2jP1iVSZf8Hf51OuYSQSd1WzipxwRe-Y0NZQDch0S1khqV1lTMG6BrSU6O6tKbeeDHhWKab4D-c1Rhe_z5PmnBF0BPI5jiPXLtD7bGv6qd-v2xOVw2UNcGOEPwXKQlFkDQBmwVojZmiuo9Bq1yjAc2UtTBGYOZ_QUMvEUXWEXMuWQAtoy5BNHfBpOZUYbDp7233aSc2_onUqRa";
        System.out.println(decodeTokenHeader(idToken));
        System.out.println(decodeTokenPayload(idToken));

         */
        TokenUtils tokenUtils = new TokenUtils();
        tokenUtils.decryptJwk();
    }

}
