package com.kurtuba.auth.utils;

import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken;
import com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.gson.GsonFactory;
import com.kurtuba.auth.data.model.AuthProvider;
import com.kurtuba.auth.data.model.ClientType;
import com.kurtuba.auth.data.model.dto.UserRegistrationDto;
import com.nimbusds.jose.shaded.gson.JsonObject;
import com.nimbusds.jose.shaded.gson.JsonParser;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import org.jose4j.jwe.JsonWebEncryption;
import org.jose4j.jwk.PublicJsonWebKey;
import org.jose4j.keys.PbkdfKey;
import org.jose4j.lang.JoseException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.util.*;

@Component
public class TokenUtils {

    @Value("${kurtuba.rsa-jwk.key}")
    private String rsaJwkKey;
    @Value("classpath:rsa-jwk")
    Resource rsaJwkFile;
    @Value("${auth.server.issuer-url}")
    private String authServerIssuerUrl;

    private PublicJsonWebKey publicJsonWebKey;

    /**
     * Generates an access token for login via rest request
     * @param userId
     * @param clientType
     * @return Access token
     */
    public String generateToken(String userId, ClientType clientType) {
        if (publicJsonWebKey == null) {
            //System.out.println("key null!");
            publicJsonWebKey = decrypJwk();
        }
        // set expiration date to 5 years later
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR,5);
        return Jwts.builder()
                .setHeader(Map.of("kid",publicJsonWebKey.getKeyId()))
                .setIssuer(authServerIssuerUrl)
                .setSubject(userId)
                .setAudience(clientType.getClientTypeName())
                .claim("jti", UUID.randomUUID())
                .setIssuedAt(new Date())
                .setNotBefore(new Date())
                .setExpiration(cal.getTime())
                //.claim("role", "user")
                .signWith(publicJsonWebKey.getPrivateKey())
                .compact();
    }

    /**
     * Returns claims of token generated by this auth server
     * Uses signing keys to verify during decoding
     * Won't work for older signing keys
     * TODO make it work for older JWTs signed by previous keys
     * @param token
     * @return
     */
    public Claims getVerifiedTokenClaims(String token){
        return Jwts.parserBuilder().setSigningKey(publicJsonWebKey.getPrivateKey()).build().parseClaimsJws(token).getBody();
    }

    private PublicJsonWebKey decrypJwk() {
        try {
            String jwkEncrypted = rsaJwkFile.getContentAsString(StandardCharsets.UTF_8);
            JsonWebEncryption decryptingJwe = new JsonWebEncryption();
            decryptingJwe.setCompactSerialization(jwkEncrypted);
            decryptingJwe.setKey(new PbkdfKey(rsaJwkKey));
            String payload = decryptingJwe.getPayload();

            return PublicJsonWebKey.Factory.newPublicJwk(payload);

        } catch (IOException | JoseException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * Decodes and verifies google access token
     *
     * @param idTokenString token given by google
     * @param clientId      clientId used to get the token(Android clientId or iOS clientId)
     * @throws GeneralSecurityException
     * @throws IOException
     */
    public static UserRegistrationDto decodeGoogleToken(String idTokenString, String clientId) throws GeneralSecurityException, IOException {
        UserRegistrationDto newUser = new UserRegistrationDto();
        GoogleIdTokenVerifier verifier = new GoogleIdTokenVerifier.Builder(new NetHttpTransport(), new GsonFactory())
                // Specify the CLIENT_ID of the app that accesses the backend:
                .setAudience(Collections.singletonList(clientId))
                // Or, if multiple clients access the backend:
                //.setAudience(Arrays.asList(CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3))
                .build();

        // (Receive idTokenString by HTTPS POST)

        GoogleIdToken idToken = verifier.verify(idTokenString);
        if (idToken != null) {
            GoogleIdToken.Payload payload = idToken.getPayload();

            // Print user identifier
            String userId = payload.getSubject();
            System.out.println("User ID: " + userId);

            // Get profile information from payload
            String email = payload.getEmail();
            String familyName = (String) payload.get("family_name");
            String givenName = (String) payload.get("given_name");
            newUser.setEmail(email);
            newUser.setName(givenName);
            newUser.setSurname(familyName);
            newUser.setAuthProvider(AuthProvider.GOOGLE);

        } else {
            System.out.println("Invalid ID token.");
        }

        return newUser;
    }

    /**
     * Generic token payload decoder
     *
     * @param tokenString
     * @return JsonObject
     */
    public static JsonObject decodeTokenPayload(String tokenString) {
        String[] split_string = tokenString.split("\\.");
        String base64EncodedBody = split_string[1];
        Base64.Decoder base64Url = Base64.getDecoder();
        String body = new String(base64Url.decode(base64EncodedBody));

        return JsonParser.parseString(body).getAsJsonObject();

    }

    public static void main(String[] args) {
        String idToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijg1MmI0Yzc0MTM1MWVlZGM2ZWM4YWU3ODNiOThlZWFiZTIxNTdkYWEifQ.eyJpc3MiOiJodHRwczpcL1wvd3d3LmZhY2Vib29rLmNvbSIsImF1ZCI6IjE3ODg1Nzc5ODA3Njc1NiIsInN1YiI6IjEwMTU5MjAxMTgwNTI3Nzk3IiwiaWF0IjoxNjg2ODMxMTU4LCJleHAiOjE2ODY4MzQ3NTgsImp0aSI6IlJ5VWMuNGM5ZWZlY2NjYTAyOWZjNjFmZDU5ZWUwZDBlODdmM2Q4ZTA0ZTgwNDU2MjUyMjE3OTZhNDBhODBiMDJkYjhiZiIsIm5vbmNlIjoiIiwiYXRfaGFzaCI6IlV1Q3V5eXNPQmsxRE1wSTY0TWppbEEiLCJlbWFpbCI6Im11cmF0Y2FuZXJcdTAwNDB5bWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiTXVyYXQiLCJmYW1pbHlfbmFtZSI6IkNhbmVyIiwibmFtZSI6Ik11cmF0IENhbmVyIiwicGljdHVyZSI6Imh0dHBzOlwvXC9wbGF0Zm9ybS1sb29rYXNpZGUuZmJzYnguY29tXC9wbGF0Zm9ybVwvcHJvZmlsZXBpY1wvP2FzaWQ9MTAxNTkyMDExODA1Mjc3OTcmaGVpZ2h0PTEwMCZ3aWR0aD0xMDAmZXh0PTE2ODk0MjMxNTkmaGFzaD1BZVFVRk5PbC02eUo5cndKU2w0In0.tC1fqzT7E_gJlSAYq9PXJYs7bQ2R03RbB2jP1iVSZf8Hf51OuYSQSd1WzipxwRe-Y0NZQDch0S1khqV1lTMG6BrSU6O6tKbeeDHhWKab4D-c1Rhe_z5PmnBF0BPI5jiPXLtD7bGv6qd-v2xOVw2UNcGOEPwXKQlFkDQBmwVojZmiuo9Bq1yjAc2UtTBGYOZ_QUMvEUXWEXMuWQAtoy5BNHfBpOZUYbDp7233aSc2_onUqRa";
        decodeTokenPayload(idToken);
    }

}
