server:
  port: 8080
  forward-headers-strategy: framework

auth:
  server:
    issuer-url: ${AUTH_SERVER_ISSUER_URL:http://localhost:8080}

logging:
  level:
    root: info

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/kurtuba_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholderReplacement: false
    schemas:
      - public
    default-schema: public
    user: ${FLYWAY_USERNAME:${DB_USERNAME:postgres}}
    password: ${FLYWAY_PASSWORD:${DB_PASSWORD:postgres}}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${auth.server.issuer-url}/auth/oauth2/jwks
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health, info, env

kurtuba:
  mail:
    from-address: ${KURTUBA_MAIL_FROM_ADDRESS:noreply@kurtuba.app}
    support-address: ${KURTUBA_MAIL_SUPPORT_ADDRESS:support@kurtuba.app}
  rate-limit:
    enabled: false
    public-api:
      registration:
        pattern: /auth/registration/**
        capacity: 100
        refill: 15m
      login:
        pattern: /auth/login
        capacity: 100
        refill: 10m
      token-refresh:
        pattern: /auth/token
        capacity: 300
        refill: 10m
      web-token-refresh:
        pattern: /auth/web/token
        capacity: 200
        refill: 10m
      password-reset:
        pattern: /auth/user/password/reset/**
        capacity: 30
        refill: 1h
      sms:
        pattern: /auth/sms/**
        capacity: 5
        refill: 15m
      verification:
        pattern: /auth/user/email/verification/link/**
        capacity: 30
        refill: 15m
  server:
    url: ${KURTUBA_SERVER_URL:http://localhost:8080}
  auth-provider:
    google:
      client-id: ${GOOGLE_CLIENT_ID:}
      client-secret: ${GOOGLE_CLIENT_SECRET:}
    facebook:
      client-id: ${FACEBOOK_CLIENT_ID:}
      client-secret: ${FACEBOOK_CLIENT_SECRET:}
  jwk:
    file: ${KURTUBA_JWK_FILE:classpath:jwk.json}
    keys: '{"32abb5cf-a1fb-4cdd-9af7-fe517a0bda47": "pkBJlIfLcEW0tvIutbZjsjwBYOZ2DkRw2Hiy5S+m+uI=", "f5a7e70c-fb73-42ab-b217-841ea4e5d5b1": "A5kZEy3jC4ChSTtbq92AsARDrqslb+J7WmWwkMevhds=", "12e87ac2-9ee3-4bab-85ca-758cbd998b26":"2lWwOTIvMxfwO1n9TwOvtuuOaTva95vmW8kyGYaoe6w="}'
  meta-change:
    email-max-try-count: 3
    sms-max-try-count: 5
    validity:
      password-reset-code:
        minutes: 60
      email:
        activation-code:
          minutes: 10080
        change-code:
          minutes: 1440
      sms:
        activation-code:
          minutes: 10
          change-code:
            minutes: 10
  job:
    email:
      send:
        max-try-count: 3
    sms:
      send:
        max-try-count: 3
  twilio:
    ireland:
      live:
        sid: ${TWILIO_IRELAND_LIVE_SID:}
        auth-token: ${TWILIO_IRELAND_LIVE_AUTH_TOKEN:}
      test:
        sid: ${TWILIO_IRELAND_TEST_SID:}
        auth-token: ${TWILIO_IRELAND_TEST_AUTH_TOKEN:}
    us:
      live:
        sid: ${TWILIO_US_LIVE_SID:}
        auth-token: ${TWILIO_US_LIVE_AUTH_TOKEN:}
      test:
        sid: ${TWILIO_US_TEST_SID:}
        auth-token: ${TWILIO_US_TEST_AUTH_TOKEN:}

    messaging-service:
      sid: ${TWILIO_MESSAGING_SERVICE_SID:}
    verify-service:
      sid: ${TWILIO_VERIFY_SERVICE_SID:}
