server:
  port: 8080
  #servlet:
   #session:
     #tracking-modes: cookie
     #persistent: false


auth:
  server:
    issuer-url: http://192.168.1.2:8080
    mobile-client-secret: $2a$10$8Xr/8v58z91sUKQcD.wmqupNP3azgAm/FFVshnq9xs9irAbHlr7Ea
    server-client-secret: $2a$10$9u/FK6u3hyYv6LfiahN.ceeKhyToICqCvxOcJgH11EzB2YcKInwta
    ip: 192.168.1.2
    port: 8080
    email-password-login-endpoint: http://${auth.server.ip}:${auth.server.port}/login

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        default_schema: kurtuba

  datasource:
    url: jdbc:postgresql://192.168.1.114:5432/postgres
    username: postgres
    password: postgres

  security:
      client:
        registration:
          google:
            clientId: 288830956764-22nplnlfceqg5m4a09mq9dvrrjvaae88.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
  mail:
    host: 192.168.1.114
    port: 1025
    username: user
    password: pass
    protocol: smtp
  data:
    redis:
      host: 192.168.1.114


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, env

kurtuba:
  rsa-jwk:
    key: "FD7pr&.f!my?k#8:"
    file: "rsa-jwk"

