server:
  port: 8080


auth:
  server:
    issuer-url: http://192.168.1.2:8080
    protocol: http://
    ip: 192.168.1.2
    port: 8080

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        default_schema: kurtuba

  datasource:
    url: jdbc:postgresql://192.168.1.114:5432/postgres
    username: kurtubauser
    password: 6kOroUVNmFqcp3I
    hikari:
      schema: kurtuba

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${auth.server.ip}:${auth.server.port}/oauth2/jwks
  mail:
    host: 192.168.1.114
    port: 1025
    username: user
    password: pass
    protocol: smtp


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, env

kurtuba:
  rsa-jwk:
    file: "rsa-jwk.json"
    secrets: '{"363ff933-15b5-4447-a78d-fa2560049cee": "FD7pr&.f!my?k#8:", "fe4ab529-e7d1-4a00-b32d-4bb4cb5776db": "dI1Q089vTAd3aAO"}'
  meta-change:
    max-try-count: 3
    validity:
      password-reset-code:
        minutes: 60
      email:
        activation-code:
          minutes: 10080
        change-code:
          minutes: 1440
  job:
    email:
      send:
        max-try-count: 3


