CREATE TABLE public.localization_supported_countries (
    id character varying(255) NOT NULL,
    country_code character varying(255) NOT NULL,
    created_date timestamp(6) without time zone NOT NULL,
    updated_date timestamp(6) without time zone
);

ALTER TABLE public.localization_supported_countries OWNER TO kurtuba_auth_migrator;

ALTER TABLE ONLY public.localization_supported_countries
    ADD CONSTRAINT localization_supported_countries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.localization_supported_countries
    ADD CONSTRAINT localization_supported_countries_country_code_key UNIQUE (country_code);

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.localization_supported_countries TO kurtuba_auth_user;

CREATE TABLE public.localization_supported_langs (
    id character varying(255) NOT NULL,
    language_code character varying(255) NOT NULL,
    created_date timestamp(6) without time zone NOT NULL,
    updated_date timestamp(6) without time zone
);

ALTER TABLE public.localization_supported_langs OWNER TO kurtuba_auth_migrator;

ALTER TABLE ONLY public.localization_supported_langs
    ADD CONSTRAINT localization_supported_langs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.localization_supported_langs
    ADD CONSTRAINT localization_supported_langs_language_code_key UNIQUE (language_code);

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.localization_supported_langs TO kurtuba_auth_user;

ALTER TABLE public.user_setting
    ADD COLUMN language_code character varying(255),
    ADD COLUMN country_code character varying(255);

INSERT INTO public.localization_supported_langs (id, language_code, created_date)
SELECT DISTINCT
       'lang-' || lower(src.language_code),
       lower(src.language_code),
       CURRENT_TIMESTAMP
FROM (
         SELECT language_code FROM public.localization_message
         UNION
         SELECT language_code FROM public.localization_available_locale
     ) src
WHERE src.language_code IS NOT NULL
ON CONFLICT (language_code) DO NOTHING;

INSERT INTO public.localization_supported_countries (id, country_code, created_date)
VALUES
    ('country-ad', 'ad', CURRENT_TIMESTAMP),
    ('country-ae', 'ae', CURRENT_TIMESTAMP),
    ('country-af', 'af', CURRENT_TIMESTAMP),
    ('country-ag', 'ag', CURRENT_TIMESTAMP),
    ('country-ai', 'ai', CURRENT_TIMESTAMP),
    ('country-al', 'al', CURRENT_TIMESTAMP),
    ('country-am', 'am', CURRENT_TIMESTAMP),
    ('country-ao', 'ao', CURRENT_TIMESTAMP),
    ('country-aq', 'aq', CURRENT_TIMESTAMP),
    ('country-ar', 'ar', CURRENT_TIMESTAMP),
    ('country-as', 'as', CURRENT_TIMESTAMP),
    ('country-at', 'at', CURRENT_TIMESTAMP),
    ('country-au', 'au', CURRENT_TIMESTAMP),
    ('country-aw', 'aw', CURRENT_TIMESTAMP),
    ('country-ax', 'ax', CURRENT_TIMESTAMP),
    ('country-az', 'az', CURRENT_TIMESTAMP),
    ('country-ba', 'ba', CURRENT_TIMESTAMP),
    ('country-bb', 'bb', CURRENT_TIMESTAMP),
    ('country-bd', 'bd', CURRENT_TIMESTAMP),
    ('country-be', 'be', CURRENT_TIMESTAMP),
    ('country-bf', 'bf', CURRENT_TIMESTAMP),
    ('country-bg', 'bg', CURRENT_TIMESTAMP),
    ('country-bh', 'bh', CURRENT_TIMESTAMP),
    ('country-bi', 'bi', CURRENT_TIMESTAMP),
    ('country-bj', 'bj', CURRENT_TIMESTAMP),
    ('country-bl', 'bl', CURRENT_TIMESTAMP),
    ('country-bm', 'bm', CURRENT_TIMESTAMP),
    ('country-bn', 'bn', CURRENT_TIMESTAMP),
    ('country-bo', 'bo', CURRENT_TIMESTAMP),
    ('country-bq', 'bq', CURRENT_TIMESTAMP),
    ('country-br', 'br', CURRENT_TIMESTAMP),
    ('country-bs', 'bs', CURRENT_TIMESTAMP),
    ('country-bt', 'bt', CURRENT_TIMESTAMP),
    ('country-bv', 'bv', CURRENT_TIMESTAMP),
    ('country-bw', 'bw', CURRENT_TIMESTAMP),
    ('country-by', 'by', CURRENT_TIMESTAMP),
    ('country-bz', 'bz', CURRENT_TIMESTAMP),
    ('country-ca', 'ca', CURRENT_TIMESTAMP),
    ('country-cc', 'cc', CURRENT_TIMESTAMP),
    ('country-cd', 'cd', CURRENT_TIMESTAMP),
    ('country-cf', 'cf', CURRENT_TIMESTAMP),
    ('country-cg', 'cg', CURRENT_TIMESTAMP),
    ('country-ch', 'ch', CURRENT_TIMESTAMP),
    ('country-ci', 'ci', CURRENT_TIMESTAMP),
    ('country-ck', 'ck', CURRENT_TIMESTAMP),
    ('country-cl', 'cl', CURRENT_TIMESTAMP),
    ('country-cm', 'cm', CURRENT_TIMESTAMP),
    ('country-cn', 'cn', CURRENT_TIMESTAMP),
    ('country-co', 'co', CURRENT_TIMESTAMP),
    ('country-cr', 'cr', CURRENT_TIMESTAMP),
    ('country-cu', 'cu', CURRENT_TIMESTAMP),
    ('country-cv', 'cv', CURRENT_TIMESTAMP),
    ('country-cw', 'cw', CURRENT_TIMESTAMP),
    ('country-cx', 'cx', CURRENT_TIMESTAMP),
    ('country-cy', 'cy', CURRENT_TIMESTAMP),
    ('country-cz', 'cz', CURRENT_TIMESTAMP),
    ('country-de', 'de', CURRENT_TIMESTAMP),
    ('country-dj', 'dj', CURRENT_TIMESTAMP),
    ('country-dk', 'dk', CURRENT_TIMESTAMP),
    ('country-dm', 'dm', CURRENT_TIMESTAMP),
    ('country-do', 'do', CURRENT_TIMESTAMP),
    ('country-dz', 'dz', CURRENT_TIMESTAMP),
    ('country-ec', 'ec', CURRENT_TIMESTAMP),
    ('country-ee', 'ee', CURRENT_TIMESTAMP),
    ('country-eg', 'eg', CURRENT_TIMESTAMP),
    ('country-eh', 'eh', CURRENT_TIMESTAMP),
    ('country-er', 'er', CURRENT_TIMESTAMP),
    ('country-es', 'es', CURRENT_TIMESTAMP),
    ('country-et', 'et', CURRENT_TIMESTAMP),
    ('country-fi', 'fi', CURRENT_TIMESTAMP),
    ('country-fj', 'fj', CURRENT_TIMESTAMP),
    ('country-fk', 'fk', CURRENT_TIMESTAMP),
    ('country-fm', 'fm', CURRENT_TIMESTAMP),
    ('country-fo', 'fo', CURRENT_TIMESTAMP),
    ('country-fr', 'fr', CURRENT_TIMESTAMP),
    ('country-ga', 'ga', CURRENT_TIMESTAMP),
    ('country-gb', 'gb', CURRENT_TIMESTAMP),
    ('country-gd', 'gd', CURRENT_TIMESTAMP),
    ('country-ge', 'ge', CURRENT_TIMESTAMP),
    ('country-gf', 'gf', CURRENT_TIMESTAMP),
    ('country-gg', 'gg', CURRENT_TIMESTAMP),
    ('country-gh', 'gh', CURRENT_TIMESTAMP),
    ('country-gi', 'gi', CURRENT_TIMESTAMP),
    ('country-gl', 'gl', CURRENT_TIMESTAMP),
    ('country-gm', 'gm', CURRENT_TIMESTAMP),
    ('country-gn', 'gn', CURRENT_TIMESTAMP),
    ('country-gp', 'gp', CURRENT_TIMESTAMP),
    ('country-gq', 'gq', CURRENT_TIMESTAMP),
    ('country-gr', 'gr', CURRENT_TIMESTAMP),
    ('country-gs', 'gs', CURRENT_TIMESTAMP),
    ('country-gt', 'gt', CURRENT_TIMESTAMP),
    ('country-gu', 'gu', CURRENT_TIMESTAMP),
    ('country-gw', 'gw', CURRENT_TIMESTAMP),
    ('country-gy', 'gy', CURRENT_TIMESTAMP),
    ('country-hk', 'hk', CURRENT_TIMESTAMP),
    ('country-hm', 'hm', CURRENT_TIMESTAMP),
    ('country-hn', 'hn', CURRENT_TIMESTAMP),
    ('country-hr', 'hr', CURRENT_TIMESTAMP),
    ('country-ht', 'ht', CURRENT_TIMESTAMP),
    ('country-hu', 'hu', CURRENT_TIMESTAMP),
    ('country-id', 'id', CURRENT_TIMESTAMP),
    ('country-ie', 'ie', CURRENT_TIMESTAMP),
    ('country-il', 'il', CURRENT_TIMESTAMP),
    ('country-im', 'im', CURRENT_TIMESTAMP),
    ('country-in', 'in', CURRENT_TIMESTAMP),
    ('country-io', 'io', CURRENT_TIMESTAMP),
    ('country-iq', 'iq', CURRENT_TIMESTAMP),
    ('country-ir', 'ir', CURRENT_TIMESTAMP),
    ('country-is', 'is', CURRENT_TIMESTAMP),
    ('country-it', 'it', CURRENT_TIMESTAMP),
    ('country-je', 'je', CURRENT_TIMESTAMP),
    ('country-jm', 'jm', CURRENT_TIMESTAMP),
    ('country-jo', 'jo', CURRENT_TIMESTAMP),
    ('country-jp', 'jp', CURRENT_TIMESTAMP),
    ('country-ke', 'ke', CURRENT_TIMESTAMP),
    ('country-kg', 'kg', CURRENT_TIMESTAMP),
    ('country-kh', 'kh', CURRENT_TIMESTAMP),
    ('country-ki', 'ki', CURRENT_TIMESTAMP),
    ('country-km', 'km', CURRENT_TIMESTAMP),
    ('country-kn', 'kn', CURRENT_TIMESTAMP),
    ('country-kp', 'kp', CURRENT_TIMESTAMP),
    ('country-kr', 'kr', CURRENT_TIMESTAMP),
    ('country-kw', 'kw', CURRENT_TIMESTAMP),
    ('country-ky', 'ky', CURRENT_TIMESTAMP),
    ('country-kz', 'kz', CURRENT_TIMESTAMP),
    ('country-la', 'la', CURRENT_TIMESTAMP),
    ('country-lb', 'lb', CURRENT_TIMESTAMP),
    ('country-lc', 'lc', CURRENT_TIMESTAMP),
    ('country-li', 'li', CURRENT_TIMESTAMP),
    ('country-lk', 'lk', CURRENT_TIMESTAMP),
    ('country-lr', 'lr', CURRENT_TIMESTAMP),
    ('country-ls', 'ls', CURRENT_TIMESTAMP),
    ('country-lt', 'lt', CURRENT_TIMESTAMP),
    ('country-lu', 'lu', CURRENT_TIMESTAMP),
    ('country-lv', 'lv', CURRENT_TIMESTAMP),
    ('country-ly', 'ly', CURRENT_TIMESTAMP),
    ('country-ma', 'ma', CURRENT_TIMESTAMP),
    ('country-mc', 'mc', CURRENT_TIMESTAMP),
    ('country-md', 'md', CURRENT_TIMESTAMP),
    ('country-me', 'me', CURRENT_TIMESTAMP),
    ('country-mf', 'mf', CURRENT_TIMESTAMP),
    ('country-mg', 'mg', CURRENT_TIMESTAMP),
    ('country-mh', 'mh', CURRENT_TIMESTAMP),
    ('country-mk', 'mk', CURRENT_TIMESTAMP),
    ('country-ml', 'ml', CURRENT_TIMESTAMP),
    ('country-mm', 'mm', CURRENT_TIMESTAMP),
    ('country-mn', 'mn', CURRENT_TIMESTAMP),
    ('country-mo', 'mo', CURRENT_TIMESTAMP),
    ('country-mp', 'mp', CURRENT_TIMESTAMP),
    ('country-mq', 'mq', CURRENT_TIMESTAMP),
    ('country-mr', 'mr', CURRENT_TIMESTAMP),
    ('country-ms', 'ms', CURRENT_TIMESTAMP),
    ('country-mt', 'mt', CURRENT_TIMESTAMP),
    ('country-mu', 'mu', CURRENT_TIMESTAMP),
    ('country-mv', 'mv', CURRENT_TIMESTAMP),
    ('country-mw', 'mw', CURRENT_TIMESTAMP),
    ('country-mx', 'mx', CURRENT_TIMESTAMP),
    ('country-my', 'my', CURRENT_TIMESTAMP),
    ('country-mz', 'mz', CURRENT_TIMESTAMP),
    ('country-na', 'na', CURRENT_TIMESTAMP),
    ('country-nc', 'nc', CURRENT_TIMESTAMP),
    ('country-ne', 'ne', CURRENT_TIMESTAMP),
    ('country-nf', 'nf', CURRENT_TIMESTAMP),
    ('country-ng', 'ng', CURRENT_TIMESTAMP),
    ('country-ni', 'ni', CURRENT_TIMESTAMP),
    ('country-nl', 'nl', CURRENT_TIMESTAMP),
    ('country-no', 'no', CURRENT_TIMESTAMP),
    ('country-np', 'np', CURRENT_TIMESTAMP),
    ('country-nr', 'nr', CURRENT_TIMESTAMP),
    ('country-nu', 'nu', CURRENT_TIMESTAMP),
    ('country-nz', 'nz', CURRENT_TIMESTAMP),
    ('country-om', 'om', CURRENT_TIMESTAMP),
    ('country-pa', 'pa', CURRENT_TIMESTAMP),
    ('country-pe', 'pe', CURRENT_TIMESTAMP),
    ('country-pf', 'pf', CURRENT_TIMESTAMP),
    ('country-pg', 'pg', CURRENT_TIMESTAMP),
    ('country-ph', 'ph', CURRENT_TIMESTAMP),
    ('country-pk', 'pk', CURRENT_TIMESTAMP),
    ('country-pl', 'pl', CURRENT_TIMESTAMP),
    ('country-pm', 'pm', CURRENT_TIMESTAMP),
    ('country-pn', 'pn', CURRENT_TIMESTAMP),
    ('country-pr', 'pr', CURRENT_TIMESTAMP),
    ('country-ps', 'ps', CURRENT_TIMESTAMP),
    ('country-pt', 'pt', CURRENT_TIMESTAMP),
    ('country-pw', 'pw', CURRENT_TIMESTAMP),
    ('country-py', 'py', CURRENT_TIMESTAMP),
    ('country-qa', 'qa', CURRENT_TIMESTAMP),
    ('country-re', 're', CURRENT_TIMESTAMP),
    ('country-ro', 'ro', CURRENT_TIMESTAMP),
    ('country-rs', 'rs', CURRENT_TIMESTAMP),
    ('country-ru', 'ru', CURRENT_TIMESTAMP),
    ('country-rw', 'rw', CURRENT_TIMESTAMP),
    ('country-sa', 'sa', CURRENT_TIMESTAMP),
    ('country-sb', 'sb', CURRENT_TIMESTAMP),
    ('country-sc', 'sc', CURRENT_TIMESTAMP),
    ('country-sd', 'sd', CURRENT_TIMESTAMP),
    ('country-se', 'se', CURRENT_TIMESTAMP),
    ('country-sg', 'sg', CURRENT_TIMESTAMP),
    ('country-sh', 'sh', CURRENT_TIMESTAMP),
    ('country-si', 'si', CURRENT_TIMESTAMP),
    ('country-sj', 'sj', CURRENT_TIMESTAMP),
    ('country-sk', 'sk', CURRENT_TIMESTAMP),
    ('country-sl', 'sl', CURRENT_TIMESTAMP),
    ('country-sm', 'sm', CURRENT_TIMESTAMP),
    ('country-sn', 'sn', CURRENT_TIMESTAMP),
    ('country-so', 'so', CURRENT_TIMESTAMP),
    ('country-sr', 'sr', CURRENT_TIMESTAMP),
    ('country-ss', 'ss', CURRENT_TIMESTAMP),
    ('country-st', 'st', CURRENT_TIMESTAMP),
    ('country-sv', 'sv', CURRENT_TIMESTAMP),
    ('country-sx', 'sx', CURRENT_TIMESTAMP),
    ('country-sy', 'sy', CURRENT_TIMESTAMP),
    ('country-sz', 'sz', CURRENT_TIMESTAMP),
    ('country-tc', 'tc', CURRENT_TIMESTAMP),
    ('country-td', 'td', CURRENT_TIMESTAMP),
    ('country-tf', 'tf', CURRENT_TIMESTAMP),
    ('country-tg', 'tg', CURRENT_TIMESTAMP),
    ('country-th', 'th', CURRENT_TIMESTAMP),
    ('country-tj', 'tj', CURRENT_TIMESTAMP),
    ('country-tk', 'tk', CURRENT_TIMESTAMP),
    ('country-tl', 'tl', CURRENT_TIMESTAMP),
    ('country-tm', 'tm', CURRENT_TIMESTAMP),
    ('country-tn', 'tn', CURRENT_TIMESTAMP),
    ('country-to', 'to', CURRENT_TIMESTAMP),
    ('country-tr', 'tr', CURRENT_TIMESTAMP),
    ('country-tt', 'tt', CURRENT_TIMESTAMP),
    ('country-tv', 'tv', CURRENT_TIMESTAMP),
    ('country-tw', 'tw', CURRENT_TIMESTAMP),
    ('country-tz', 'tz', CURRENT_TIMESTAMP),
    ('country-ua', 'ua', CURRENT_TIMESTAMP),
    ('country-ug', 'ug', CURRENT_TIMESTAMP),
    ('country-um', 'um', CURRENT_TIMESTAMP),
    ('country-us', 'us', CURRENT_TIMESTAMP),
    ('country-uy', 'uy', CURRENT_TIMESTAMP),
    ('country-uz', 'uz', CURRENT_TIMESTAMP),
    ('country-va', 'va', CURRENT_TIMESTAMP),
    ('country-vc', 'vc', CURRENT_TIMESTAMP),
    ('country-ve', 've', CURRENT_TIMESTAMP),
    ('country-vg', 'vg', CURRENT_TIMESTAMP),
    ('country-vi', 'vi', CURRENT_TIMESTAMP),
    ('country-vn', 'vn', CURRENT_TIMESTAMP),
    ('country-vu', 'vu', CURRENT_TIMESTAMP),
    ('country-wf', 'wf', CURRENT_TIMESTAMP),
    ('country-ws', 'ws', CURRENT_TIMESTAMP),
    ('country-ye', 'ye', CURRENT_TIMESTAMP),
    ('country-yt', 'yt', CURRENT_TIMESTAMP),
    ('country-za', 'za', CURRENT_TIMESTAMP),
    ('country-zm', 'zm', CURRENT_TIMESTAMP),
    ('country-zw', 'zw', CURRENT_TIMESTAMP)
ON CONFLICT (country_code) DO NOTHING;

UPDATE public.user_setting us
SET language_code = lower(lal.language_code),
    country_code = lower(lal.country_code)
FROM public.localization_available_locale lal
WHERE us.localization_available_locale_id = lal.id;

ALTER TABLE public.user_setting
    DROP CONSTRAINT IF EXISTS fke5l3m1e4mhqe2f2d1ywqe3wko;

ALTER TABLE public.user_setting
    DROP COLUMN localization_available_locale_id;

DROP TABLE public.localization_available_locale;
